project:
  type: website

website:
  title: "Behind My Code"
  description: "A blog about how technological curiosity shapes my development adventure"
  google-analytics: "G-XBYLY9KNL7"
  favicon: favicon.png
  twitter-card: true
  open-graph: true
  site-url: https://temaput.github.io/Blog/
  navbar:
    right:
      - href: https://temaput.github.io/
        text: About Me
      - icon: github
        href: https://github.com/temaput/
      - icon: linkedin
        href: https://www.linkedin.com/in/temaput/
format:
  html:
    theme: slate
    css: styles.css



