project:
  type: website

website:
  title: "Artem Putilov"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - projects-list.qmd
      - href: https://temaput.github.io/Blog
        text: Blog

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



