project:
  type: website

website:
  title: "Artem Putilov"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - projects-list.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



